server:
  port: 7070
  servlet:
    context-path: /api
  url:
    prefix: /api
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/d2p_pm?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    hikari:
      auto-commit: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  #flyway 配置，自动数据库升级
  flyway:
    clean-disabled: false
    baselineOnMigrate: true

uploader:
  qiniu:
    accessKey: 你的七牛accessKey
    secretKey: 你的七牛secretKey
    bucket: d2p-demo
  cos:
    secretId: 你的Cos secretId
    secretKey: 你的Cos secretKey
    bucket: d2p-demo-1251260344
  alioss:
    accessKey: 你的阿里云 accessKey
    accessKeySecret: 你的阿里云 accessKeySecret
    bucket: d2p-demo
    endpoint: oss-cn-shenzhen.aliyuncs.com
    # 你的阿里云ram角色id
    roleArn: "acs:ram::1831228848739566:role/ramosstemp"

# 是否禁止修改数据
demo:
  editDisabled: false

security:
  # 默认为 authorization ，d2-admin示例中为X-Token
  tokenHeader: "authorization"
  # 默认为 "Bearer " ，d2-admin示例中无prefix
  tokenPrefix: ""
  # 这里设置jwt的密钥
  jwtSecret: yourSecret
  jwtIssuer: greper
  #token有效期一天
  tokenExpiration: 86400

logging:
  level:
    com.veryreader: DEBUG
    com.ibatis: DEBUG
    com.ibatis.common.jdbc.SimpleDataSource: DEBUG
    com.ibatis.sqlmap.engine.impl.SqlMapClientDelegate: DEBUG
